### PR TITLE
Prevent Sass from being outputted to _site

### PR DESCRIPTION
**Pull request by libhide**
I updated the Sass folder structure to prevent 0-tools, 1-base etc. from being outputted into the _site folder when serving the website. IMO, a single CSS file looks much cleaner under _site!

### CODE REVIEW

**Comment by zagortenay333** [comment]
There is no need to add the underscore to so many files. All you have to do is exclude the entire `assets/css` folder in the `_config.yml` file and use `keep_file` option to include the `assets/css/main.css` back in.

``` yml
keep_files: ["assets/css/main.css"]
exclude: ["assets/css"]
```

**Comment by enociz** [comment]
@zagortenay333, am I right in saying that your solution is included in #2?

**Comment by zagortenay333** [comment]
No I didn't include in my pull request. You can just amend this one.

**Comment by enociz** [comment]
Ok

**Comment by libhide** [comment]
Do you suggest I go back to removing the underscores and switching to using _config?

**Comment by enociz** [comment]
I'm pretty sure that that's what @zagortenay333 meant

**Comment by zagortenay333** [comment]
Yeah, just update the pull request.

**Comment by libhide** [comment]
I updated the config file like you said and for some reason it has stopped outputting the css folder to _site. This is what I did:

1) Removed all the underscores I put in earlier.
2) Reverted to the old gulpfile.
3) Added the following to _config.yml –

```YAML
keep_files: ["assets/css/main.css"]
exclude: ["assets/css"]
```

What am I doing wrong?

**Comment by enociz** [comment]
You've removed your comment, @libhide . Am I right in presuming that you have found a fix?

**Comment by libhide** [comment]
@enociz Indeed. Will update the pull request in bit. Sorry about that!

**Comment by enociz** [comment]
The details page for your latest commit says that main.css has been deleted. Could you explain why?

**Comment by zagortenay333** [comment]
I think you should probably squash these commits into a single commit.

**Comment by libhide** [comment]
@zagortenay333 I tried squashing. This is the first time I've done this so let me know if it worked. I still see 4 commits up top.

@enociz I think the main.css file is creates when gulp-sass compiles main.scss so it shouldn't be an issue.

**Comment by zagortenay333** [comment]
You did squash them but you didn't force-push them to your fork, you merged them instead. Now you're stuck with the previous 2 commits, the new combined commit, and a merge commit. Looks pretty messy to me.

Instead of resetting, and squashing again, I think that you should just hard-reset your local branch prior to making any commits and start all over again; it's probably faster that way. So:

```
$ git reset --hard dae2262
$ git remote add upstream https://github.com/travisneilson/Design-Code.git
$ git pull upstream master
```

Now make this new commit (editing `_config.yml`.)

Force-push it into your fork in order to rewrite the commit history:

```
$ git push -f origin
```

**Comment by libhide** [comment]
@zagortenay333 Thanks a lot for helping out! 
@travisneilson The conversation here might be a little confusing. Sorry about that.

**Comment by zagortenay333** [comment]
You should't remove the last newline character from files. Notice that github even shows a little red arrow there.

**Comment by enociz** [comment]
👍 🆒

**Comment by libhide** [comment]
I noticed that Travis fixed this issue in one of the recent videos. So, I'm closing this pull request.

**Pull request closed without merging**
